# version: '3'
# services:
#   my-app:
#     image: hkotak93/articles:${IMAGE_VERSION}-local
#     command: ["./node_modules/.bin/nodemon", "server.js"]
#     container_name: my-app
#     volumes:
#       - ".:/app/:rw"
#     env_file: .env
#     environment:
#       NODE_ENV: development
#     ports:
#       - "5000:${PORT}"
#     networks:
#       - my-app-network

# networks:
#   my-app-network:


# INCORPORATING_KNEX
version: '3'
services:
  my-app:
    image: hkotak/articles:${IMAGE_VERSION}-local
    depends_on:
      - db
    command: ["./node_modules/.bin/nodemon", "app.js"]
    container_name: my-app
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - my-app-network
  db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network
volumes: 
  pg-data-volume:
networks:
  my-app-network:


